require 'addressable/uri'
require 'date'
require 'erb'
require 'fileutils'
require 'logger'
require 'json'
require 'net/http'
require 'oauth'
require 'ohm'
require 'ohm/contrib'
require 'pry'
require 'pry-nav'
require 'rest_client'
require 'securerandom'
require 'singleton'
require 'term/ansicolor'
require 'thor'
require 'virtus'
require 'yajl'
require 'yaml'

require_relative 'configuration'
require_relative 'debug'

require_relative 'api/endpoints'
require_relative 'api/oauth_settings'
require_relative 'api/headers'
require_relative 'api/request'
require_relative 'api/error_response'
require_relative 'api/response'
require_relative 'api/client'

require_relative 'helpers/decorator_helpers'
require_relative 'helpers/model_helpers'
require_relative 'helpers/remote_model_helpers'

require_relative 'remote/adaptors/resource'
require_relative 'remote/adaptors/board'
require_relative 'remote/adaptors/card'
require_relative 'remote/adaptors/comment'
require_relative 'remote/adaptors/list'
require_relative 'remote/adaptors/member'

require_relative 'remote/persistence/board'
require_relative 'remote/persistence/card'
require_relative 'remote/persistence/comment'
require_relative 'remote/persistence/list'
require_relative 'remote/persistence/move_card'

require_relative 'remote/retrieval/resource'
require_relative 'remote/retrieval/board'
require_relative 'remote/retrieval/card'
require_relative 'remote/retrieval/comment'
require_relative 'remote/retrieval/list'
require_relative 'remote/retrieval/member'

require_relative 'decorators/board'
require_relative 'decorators/card'
require_relative 'decorators/comment'
require_relative 'decorators/list'
require_relative 'decorators/member'

require_relative 'presentation/sentence'
require_relative 'presentation/template'

require_relative 'presenters/board'
require_relative 'presenters/card'
require_relative 'presenters/comment'
require_relative 'presenters/list'
require_relative 'presenters/member'

require_relative 'models/behaviours/set_default'

require_relative 'models/persistence/resource'

require_relative 'remote/all'

require_relative 'models/retrieval/resource'
require_relative 'models/retrieval/board'
require_relative 'models/retrieval/card'
require_relative 'models/retrieval/comment'
require_relative 'models/retrieval/list'
require_relative 'models/retrieval/member'

require_relative 'models/board'
require_relative 'models/card'
require_relative 'models/comment'
require_relative 'models/list'
require_relative 'models/member'
require_relative 'models/refresh'

require_relative 'commands/show/show_boards'
require_relative 'commands/show/show_comments'
require_relative 'commands/show'

require_relative 'commands/commands'
require_relative 'commands/default'
require_relative 'commands/refresh'
require_relative 'commands/status'

require_relative 'cli/thor_fixes'
require_relative 'cli/add'
require_relative 'cli/default'
require_relative 'cli/refresh'
require_relative 'cli/show'
require_relative 'cli/main'
