en:
  add:
    board:
    card:
    comment:
    list:
  default:
    board:
    card:
    list:
  main:
    init:
    status:
    config:
    cleanup:
    version:
    move:
  refresh:
    all:
    board:
    card:
    list:
  show:
    boards:
    board:
    list:
    card:
    comments: