version_1:
  board_by_id: /boards/526d8e130a14a9d846001d96
  boards_all: /members/gavinlaking1/boards
  card_by_card_id: /cards/526d8f19ddb279532e005259
  cards_by_board_id: /boards/526d8e130a14a9d846001d96/cards?filter=open
  cards_by_list_id: /lists/526d8e130a14a9d846001d97/cards?filter=open
  comments_by_board_id: /boards/526d8e130a14a9d846001d96/actions?filter=commentCard
  comments_by_card_id: /cards/526d8f19ddb279532e005259/actions?filter=commentCard
  comments_by_list_id: /lists/526d8e130a14a9d846001d97/actions?filter=commentCard
  create_board: /boards
  create_card: /cards
  create_comment: /cards/526d8f19ddb279532e005259/actions/comments
  create_list: /lists
  list_by_list_id: /lists/526d8e130a14a9d846001d97
  lists_by_board_id: /boards/526d8e130a14a9d846001d96/lists?filter=open
  member_by_member_id: /members/5195fdb5a8c01a2318004f5d
  members_by_board_id: /boards/526d8e130a14a9d846001d96/members?filter=all
  move_card: /cards/526d8f19ddb279532e005259/idList
