version_1:
  boards_all: /members/gavinlaking1/boards
  board_by_id: '/boards/%{external_id}'
  card_by_card_id: '/cards/%{external_id}'
  cards_by_board_id: '/boards/%{external_id}/cards'
  cards_by_list_id: '/lists/%{external_id}/cards'
  comments_by_board_id: '/boards/%{external_id}/actions'
  comments_by_card_id: '/cards/%{external_id}/actions'
  comments_by_list_id: '/lists/%{external_id}/actions'
  list_by_list_id: '/lists/%{external_id}'
  lists_by_board_id: '/boards/%{external_id}/lists'
  member_by_member_id: '/members/%{external_id}'
  members_by_board_id: '/boards/%{external_id}/members'
  create_board: '/boards'
  create_card: '/cards'
  create_comment: '/cards/%{external_id}/actions/comments'
  create_list: '/lists'
  move_card: '/cards/%{external_id}/idList'
