default:
  name: My Example Configuration
  api_url: https://api.trello.com/1
  api_key: some_key
  api_token: some_secret
  api_oauth_token: some_oauth_token
  api_oauth_token_secret: some_oauth_token_secret
  database: 1
  allow_remote: true
  logs: true
test:
  name: My Example Test Configuration
  api_url: https://api.trello.com/1
  api_key: some_key
  api_token: some_secret
  api_oauth_token: some_oauth_token
  api_oauth_token_secret: some_oauth_token_secret
  database: 2
  allow_remote: true
  logs: true
